
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author VISHALROSHAN
 */
public class trains_available extends javax.swing.JFrame {
    public String pay_mode = "";
    /**
     * Creates new form trains_available
     */
    public trains_available() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cnfm_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bank_transfer_check = new javax.swing.JCheckBox();
        gpay_check = new javax.swing.JCheckBox();
        name_lb = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        card_num_lb = new javax.swing.JLabel();
        card_num_text = new javax.swing.JTextField();
        cvv_text = new javax.swing.JPasswordField();
        cvv_lb = new javax.swing.JLabel();
        valid_lb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        upi_label = new javax.swing.JLabel();
        upi_text = new javax.swing.JTextField();
        valid_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Trains Available :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PNR No.", "From", "To", "Date", "Class"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        cnfm_btn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cnfm_btn.setText("Confirm");
        cnfm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnfm_btnActionPerformed(evt);
            }
        });

        cancel_btn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Select Payment Mode :\n");

        bank_transfer_check.setText("Bank Transfer");
        bank_transfer_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bank_transfer_checkActionPerformed(evt);
            }
        });

        gpay_check.setText("Online Payment");
        gpay_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpay_checkActionPerformed(evt);
            }
        });

        name_lb.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        name_lb.setText("Name on card :");

        name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textActionPerformed(evt);
            }
        });

        card_num_lb.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        card_num_lb.setText("Card Number :");

        card_num_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card_num_textActionPerformed(evt);
            }
        });

        cvv_lb.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cvv_lb.setText("Enter CVV :");

        valid_lb.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        valid_lb.setText("Valid thru. :");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        upi_label.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        upi_label.setText("UPI ID :");

        upi_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upi_textActionPerformed(evt);
            }
        });

        valid_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valid_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bank_transfer_check))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name_lb)
                                        .addComponent(card_num_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cvv_lb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(valid_lb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(card_num_text)
                                        .addComponent(name_text)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cvv_text, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(valid_text, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gpay_check))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(upi_label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(upi_text, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(cnfm_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel_btn)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bank_transfer_check)
                    .addComponent(gpay_check))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_lb)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(card_num_lb)
                    .addComponent(card_num_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvv_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvv_lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valid_lb)
                    .addComponent(valid_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upi_label)
                    .addComponent(upi_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnfm_btn)
                    .addComponent(cancel_btn))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    static int id_q11 = 101;
    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:cancel button
        JOptionPane.showMessageDialog(cancel_btn, "Ticket canceled");
        this.dispose();
        booking_page bt = new booking_page();
        bt.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_cancel_btnActionPerformed
    static String bool = "";
    public void date_class(String flag){
        bool = flag;
    }
    private void cnfm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnfm_btnActionPerformed
        // TODO add your handling code here:confirm button
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selected_row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        int value =(int) model.getValueAt(selected_row, column);   
        System.out.println("PNR no.:"+value);      
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://root@127.0.0.1:3306/book_ticket", "local", "");
            Statement st = con.createStatement();
            String query = "update `booked` set pnrnum="+value+" where id="+id_q11;
            st.executeUpdate(query);
            if(bool.equals("true")){
                String query1 = "update `booked` set dateoftravel=(select date_res from `reservation` where pnr="+value+"),class =(select class from `reservation` where pnr="+value+") where id="+id_q11;
                st.executeUpdate(query1);
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(trains_available.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(cnfm_btn, "Ticket Booked");
        this.dispose();
        booking_page bt = new booking_page();
        bt.setVisible(true);
    }//GEN-LAST:event_cnfm_btnActionPerformed

    private void name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textActionPerformed

    private void card_num_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card_num_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card_num_textActionPerformed

    private void upi_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upi_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upi_textActionPerformed

    private void bank_transfer_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bank_transfer_checkActionPerformed
        // TODO add your handling code here:
        
        if(bank_transfer_check.isSelected()){
            pay_mode = "Bank Transfer";
            upi_label.setVisible(false);
            upi_text.setVisible(false);
            name_lb.setVisible(true);
            card_num_lb.setVisible(true);
            cvv_lb.setVisible(true);
            valid_lb.setVisible(true);
            name_text.setVisible(true);
            card_num_text.setVisible(true);
            cvv_text.setVisible(true);
            valid_text.setVisible(true);
            gpay_check.setVisible(false);
            bank_transfer_check.setEnabled(false);
        } 
        int amount = (int) ((Math.random() * (8000 - 2500)) + 2500);
        double gst = (double) (amount*0.05);
        double total=amount+gst;
        jTextArea1.append("Ticket Price\t:\t"+amount+
                        "\n"+
                        "\nGST\t:\t0.05%"+
                        "\n"+
                        "\n"+
                                        "\t\t- - - - - - - - -"+
                        "\nTotal amount\t:\tRs. "+total+
                        "\n"+
                                        "\t\t- - - - - - - - -"
            );
        System.out.println("Amount :"+total);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://root@127.0.0.1:3306/book_ticket", "local", "");
            Statement st = con.createStatement();
            String query = "update `booked` set amount="+total+"where id="+id_q11;
            st.executeUpdate(query);
        } catch (SQLException ex) {
            Logger.getLogger(trains_available.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ticket_info t = new ticket_info();
        t.pay(pay_mode);
        t.amt(total);
    }//GEN-LAST:event_bank_transfer_checkActionPerformed

    private void gpay_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpay_checkActionPerformed
        // TODO add your handling code here:
        if(gpay_check.isSelected()){
            pay_mode = "Online Payment";
            name_lb.setVisible(false);
            card_num_lb.setVisible(false);
            cvv_lb.setVisible(false);
            valid_lb.setVisible(false);
            name_text.setVisible(false);
            card_num_text.setVisible(false);
            cvv_text.setVisible(false);
            valid_text.setVisible(false);
            upi_label.setVisible(true);
            upi_text.setVisible(true);
            bank_transfer_check.setVisible(false);
            gpay_check.setEnabled(false);
        }        
        int amount = (int) ((Math.random() * (8000 - 2500)) + 2500);
        double gst = (double) (amount*0.05);
        double total = amount+gst;
        jTextArea1.append("Ticket Price\t:\t"+amount+
                        "\n"+
                        "\nGST\t:\t0.05%"+
                        "\n"+
                        "\n"+
                                        "\t\t- - - - - - - - -"+
                        "\nTotal amount\t:\tRs. "+total+
                        "\n"+
                                        "\t\t- - - - - - - - -"
            );
        System.out.println("Amount :"+total);   
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://root@127.0.0.1:3306/book_ticket", "local", "");
            Statement st = con.createStatement();
            String query = "update `booked` set amount="+total+"where id="+id_q11;
            st.executeUpdate(query);
        } catch (SQLException ex) {
            Logger.getLogger(trains_available.class.getName()).log(Level.SEVERE, null, ex);
        }
        ticket_info t = new ticket_info();
        t.pay(pay_mode);
        t.amt(total);
    }//GEN-LAST:event_gpay_checkActionPerformed

    private void valid_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valid_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valid_textActionPerformed
    public void update(Object[] n, int i, int id_q1){        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();                
        model.insertRow(i, n);
        id_q11 = id_q1;
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trains_available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trains_available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trains_available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trains_available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trains_available().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bank_transfer_check;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel card_num_lb;
    private javax.swing.JTextField card_num_text;
    private javax.swing.JButton cnfm_btn;
    private javax.swing.JLabel cvv_lb;
    private javax.swing.JPasswordField cvv_text;
    private javax.swing.JCheckBox gpay_check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel name_lb;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel upi_label;
    private javax.swing.JTextField upi_text;
    private javax.swing.JLabel valid_lb;
    private javax.swing.JTextField valid_text;
    // End of variables declaration//GEN-END:variables
}
